title: Yu-Cian Tsai
description: PhD candidate 
url: "https://github.com/yucian1997/yuciantsai.git"  # Change to your GitHub Pages URL
paginate: 5
permalink: pretty
avatar: /avatar.jpeg
cover_image: /bg.jpeg

plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optional: additional configurations for the theme
# For more options, refer to the theme's documentation

#remote_theme: vszhub/not-pure-poole
remote_theme: yucian1997/yctsai
